### ISSUE TITLE
Missing track

### ISSUE THREAD

**Issue by frntc** [tebl/C64-Stereo-SID#1]
Hi,

first of all, thanks for sharing your project(s)!

I noticed that there's a missing track between D1 and R1 in your .pcb layout, but this can easily fixed by a wire on the bottom side ;-)

I was wondering if you tested with a SwinSID Nano as 2nd SID (or 2 Nanos), as I got weird sounds. Is it possible that it's related to its PWM output?

**Comment by tebl** [comment]
I have not tested with the SwinSID boards as I did not like the sound coming out of the one I had, but might might have to put checking with it on a list - if I can remember which machine I left it inside. From what I can remember it had wierd notes that dropped before the end, but that was the only SID in the system.

Anyway, thank you for figuring out the missing trace - there's always one little details than sneaks in after you've paid for the order.

**Comment by frntc** [comment]
Did your SwinSID have the latest firmware? Especially early versions sound bad...

**Comment by tebl** [comment]
Couldn't find the SwinSID, may have sold the machine around it at some point. It was one of the early ones, may have find a new one to try out :-)
